// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.23/esri/copyright.txt for details.
//>>built
require({cache:{"dojo/debounce":function(){define([],function(){return function(q,y){var k;return function(){k&&clearTimeout(k);var f=this,l=arguments;k=setTimeout(function(){q.apply(f,l)},y)}}})},"esri/numberUtils":function(){define(["dojo/has","dojo/number","dojo/i18n!dojo/cldr/nls/number","./kernel"],function(q,y,k,f){var l=function(f,n){return f-n},A={_reNumber:/^-?(\d+)(\.(\d+))?$/i,getDigits:function(f){var n=String(f),h=n.match(A._reNumber);f={integer:0,fractional:0};h&&h[1]?(f.integer=h[1].split("").length,
f.fractional=h[3]?h[3].split("").length:0):-1<n.toLowerCase().indexOf("e")&&(h=n.split("e"),n=h[0],h=h[1],n&&h&&(n=Number(n),h=Number(h),(f=0<h)||(h=Math.abs(h)),n=A.getDigits(n),f?(n.integer+=h,n.fractional=h>n.fractional?0:n.fractional-h):(n.fractional+=h,n.integer=h>n.integer?1:n.integer-h),f=n));return f},getFixedNumbers:function(f,n){var h,k;h=Number(f.toFixed(n));h<f?k=h+1/Math.pow(10,n):(k=h,h-=1/Math.pow(10,n));h=Number(h.toFixed(n));k=Number(k.toFixed(n));return[h,k]},getPctChange:function(f,
k,h,l){var n={prev:null,next:null},z;null!=h&&(z=f-h,n.prev=Math.floor(Math.abs(100*(k-h-z)/z)));null!=l&&(z=l-f,n.next=Math.floor(Math.abs(100*(l-k-z)/z)));return n},round:function(f,k){var h=f.slice(0),n,z,q,y,v,d,w,r,t,L=k&&null!=k.tolerance?k.tolerance:2,G=k&&k.indexes,x=k&&null!=k.strictBounds?k.strictBounds:!1;if(G)G.sort(l);else for(G=[],d=0;d<h.length;d++)G.push(d);for(d=0;d<G.length;d++)if(t=G[d],n=h[t],z=0===t?null:h[t-1],q=t===h.length-1?null:h[t+1],y=A.getDigits(n),y=y.fractional){w=0;
for(r=!1;w<=y&&!r;)v=A.getFixedNumbers(n,w),v=x&&0===d?v[1]:v[0],r=A.hasMinimalChange(n,v,z,q,L),w++;r&&(h[t]=v)}return h},hasMinimalChange:function(f,k,h,l,q){f=A.getPctChange(f,k,h,l);k=null==f.prev||f.prev<=q;h=null==f.next||f.next<=q;return k&&h||f.prev+f.next<=2*q},_reAllZeros:new RegExp("\\"+k.decimal+"0+$","g"),_reSomeZeros:RegExp("(\\d)0*$","g"),format:function(f,k){k=k||{places:20,round:-1};var h=y.format(f,k);h&&(h=h.replace(A._reSomeZeros,"$1").replace(A._reAllZeros,""));return h}};q("extend-esri")&&
(f.numberUtils=A);return A})},"esri/renderers/utils":function(){define("dojo/_base/lang dojo/_base/array dojo/has dojo/date/locale ../kernel ../numberUtils ../Color dojo/i18n!dojo/cldr/nls/gregorian".split(" "),function(q,y,k,f,l,A,z,n){function h(d){return d&&y.map(d,function(d){return new z(d)})}function O(d,t,f){var r="";0===t?r=I.lt+" ":t===f&&(r=I.gt+" ");return r+d}var D={},I={lte:"\x3c\x3d",gte:"\x3e\x3d",lt:"\x3c",gt:"\x3e",pct:"%"},K={millisecond:0,second:1,minute:2,hour:3,day:4,month:5,
year:6},v={millisecond:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},second:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},minute:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},hour:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},day:{selector:"date",dateOptions:{formatLength:"long"}},month:{selector:"date",dateOptions:{formatLength:"long"}},year:{selector:"date",dateOptions:{selector:"year"}}},d={formatLength:"short",
fullYear:!0},w={formatLength:"short"};q.mixin(D,{timelineDateFormatOptions:{selector:"date",dateOptions:{formatLength:"short",fullYear:!0}},formatDate:function(r,t){var k,h=[];null==r||r instanceof Date||(r=new Date(r));t=t||{};t=q.mixin({},t);var x=t.selector?t.selector.toLowerCase():null;k=!x||-1<x.indexOf("time");x=!x||-1<x.indexOf("date");k&&(t.timeOptions=t.timeOptions||w,t.timeOptions&&(t.timeOptions=q.mixin({},t.timeOptions),t.timeOptions.selector=t.timeOptions.selector||"time",h.push(t.timeOptions)));
x&&(t.dateOptions=t.dateOptions||d,t.dateOptions&&(t.dateOptions=q.mixin({},t.dateOptions),t.dateOptions.selector=t.dateOptions.selector||"date",h.push(t.dateOptions)));h&&h.length?(h=y.map(h,function(d){return f.format(r,d)}),k=1==h.length?h[0]:n["dateTimeFormat-medium"].replace(/\'/g,"").replace(/\{(\d+)\}/g,function(d,f){return h[f]})):k=f.format(r);return k},createColorStops:function(d){var f=d.values,r=d.colors,k=d.labelIndexes,h=d.isDate,l=d.dateFormatOptions;d=[];return d=y.map(f,function(d,
t){var x=null;if(!k||-1<y.indexOf(k,t)){var n;(n=h?D.formatDate(d,l):A.format(d))&&(x=O(n,t,f.length-1))}return{value:d,color:r[t],label:x}})},updateColorStops:function(d){var f=d.stops,r=d.changes,k=d.isDate,h=d.dateFormatOptions,l=[],n,q=y.map(f,function(d){return d.value});y.forEach(r,function(d){l.push(d.index);q[d.index]=d.value});n=A.round(q,{indexes:l});y.forEach(f,function(d,t){d.value=q[t];if(null!=d.label){var r,x=null;(r=k?D.formatDate(n[t],h):A.format(n[t]))&&(x=O(r,t,f.length-1));d.label=
x}})},createClassBreakLabel:function(d){var f=d.minValue,k=d.maxValue,r=d.isFirstBreak?"":I.gt+" ";d="percent-of-total"===d.normalizationType?I.pct:"";f=null==f?"":A.format(f);k=null==k?"":A.format(k);return r+f+d+" \u2013 "+k+d},setLabelsForClassBreaks:function(d){var f=d.classBreaks,k=d.classificationMethod,r=d.normalizationType,h=[];f&&f.length&&("standard-deviation"===k?console.log("setLabelsForClassBreaks: cannot set labels for class breaks generated using 'standard-deviation' method."):d.round?
(h.push(f[0].minValue),y.forEach(f,function(d){h.push(d.maxValue)}),h=A.round(h),y.forEach(f,function(d,f){d.label=D.createClassBreakLabel({minValue:0===f?h[0]:h[f],maxValue:h[f+1],isFirstBreak:0===f,normalizationType:r})})):y.forEach(f,function(d,f){d.label=D.createClassBreakLabel({minValue:d.minValue,maxValue:d.maxValue,isFirstBreak:0===f,normalizationType:r})}))},updateClassBreak:function(d){var f=d.classBreaks,k=d.normalizationType,h=d.change,r=h.index,h=h.value,l=-1,n=-1,q=f.length;"standard-deviation"===
d.classificationMethod?console.log("updateClassBreak: cannot update labels for class breaks generated using 'standard-deviation' method."):(0===r?l=r:r===q?n=r-1:(n=r-1,l=r),-1<l&&l<q&&(d=f[l],d.minValue=h,d.label=D.createClassBreakLabel({minValue:d.minValue,maxValue:d.maxValue,isFirstBreak:0===l,normalizationType:k})),-1<n&&n<q&&(d=f[n],d.maxValue=h,d.label=D.createClassBreakLabel({minValue:d.minValue,maxValue:d.maxValue,isFirstBreak:0===n,normalizationType:k})))},calculateDateFormatInterval:function(d){var f,
k,h=d.length,r,l,n,q,v,w,z=Infinity,A;d=y.map(d,function(d){return new Date(d)});for(f=0;f<h-1;f++){r=d[f];n=[];v=Infinity;w="";for(k=f+1;k<h;k++)l=d[k],l=r.getFullYear()!==l.getFullYear()&&"year"||r.getMonth()!==l.getMonth()&&"month"||r.getDate()!==l.getDate()&&"day"||r.getHours()!==l.getHours()&&"hour"||r.getMinutes()!==l.getMinutes()&&"minute"||r.getSeconds()!==l.getSeconds()&&"second"||"millisecond",q=K[l],q<v&&(v=q,w=l),n.push(l);v<z&&(z=v,A=w)}return A},createUniqueValueLabel:function(d){var f=
d.value,k=d.fieldInfo,h=d.domain;d=d.dateFormatInterval;var l=String(f);(h=h&&h.codedValues?h.getName(f):null)?l=h:"number"===typeof f&&(l=k&&"esriFieldTypeDate"===k.type?D.formatDate(f,d&&v[d]):A.format(f));return l},cloneColorInfo:function(d){var f;d&&(f=q.mixin({},d),f.colors=h(f.colors),f.stops=f.stops&&y.map(f.stops,function(d){d=q.mixin({},d);d.color&&(d.color=new z(d.color));return d}),f.legendOptions&&(f.legendOptions=q.mixin({},f.legendOptions)));return f},cloneOpacityInfo:function(d){var f;
if(d){f=q.mixin({},d);if(d=f.opacityValues)f.opacityValues=d.slice(0);if(d=f.stops)f.stops=y.map(d,function(d){return q.mixin({},d)});if(d=f.legendOptions)f.legendOptions=q.mixin({},d)}return f},cloneSizeInfo:function(d){var f;d&&(f=q.mixin({},d),f.stops&&(f.stops=y.map(f.stops,function(d){return q.mixin({},d)})),(d=f.minSize)&&"object"===typeof d&&(f.minSize=D.cloneSizeInfo(d)),(d=f.maxSize)&&"object"===typeof d&&(f.maxSize=D.cloneSizeInfo(d)),d=f.legendOptions)&&(f.legendOptions=q.mixin({},d),d=
d.customValues)&&(f.legendOptions.customValues=d.slice(0));return f}});k("extend-esri")&&q.setObject("renderer.utils",D,l);return D})},"*noref":1}});
define("esri/dijit/Legend","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/_base/Color dojo/debounce dojo/has dojo/sniff dojo/Deferred dojo/DeferredList dojo/json dojo/dom dojo/dom-construct dojo/dom-style dojo/dom-class dijit/_Widget dojox/gfx dojox/gfx/matrix dojox/html/entities ../kernel ../config ../request ../lang ../numberUtils ../renderers/utils ../renderers/SimpleRenderer ../renderers/UniqueValueRenderer ../renderers/ClassBreaksRenderer ../renderers/ScaleDependentRenderer ../renderers/DotDensityRenderer ../renderers/TemporalRenderer ../renderers/VectorFieldRenderer ../renderers/HeatmapRenderer ../symbols/PictureFillSymbol ../symbols/SimpleLineSymbol ../symbols/jsonUtils ../renderers/jsonUtils ./_EventedWidget dojo/i18n!../nls/jsapi".split(" "),function(q,
y,k,f,l,A,z,n,h,O,D,I,K,v,d,w,r,t,L,G,x,T,Q,P,J,F,M,Y,Z,aa,ba,ca,da,R,ea,U,V,N,W,X,S){var H=y([X,t],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,_preserveCacheOnDestroy:!1,dotDensitySwatchSize:26,dotCoverage:75,gradientHeight:30,transparencyRampColor:new z([64,64,64]),defaultText:"Aa",sizeRampLightColor:new z([255,255,255]),sizeRampDarkColor:new z([128,128,128]),layerConnects:[],gradientWidth:34,colorRampBorder:"1px solid",_specialChars:{lt:"\x3c",
gt:"\x3e"},_ieTimer:100,_isRightToLeft:!1,_align:null,_legendAlign:null,constructor:function(a,b){k.mixin(this,S.widgets.legend);this._i18n=S.widgets.legend;a=a||{};a.map?b?(this.map=a.map,this.layerInfos=a.layerInfos,this._respectCurrentMapScale=!1===a.respectCurrentMapScale?!1:!0,this._respectVisibility=!1===a.respectVisibility?!1:!0,this._preserveCacheOnDestroy=a.preserveCacheOnDestroy?!0:!1,this.arrangement=a.arrangement===H.ALIGN_RIGHT?H.ALIGN_RIGHT:H.ALIGN_LEFT,this.arrangement===H.ALIGN_RIGHT&&
(this.alignRight=!0),this.autoUpdate=!1===a.autoUpdate?!1:!0,this._surfaceItems=[],this.hideLayersInLegend={},this.refresh=n(this.refresh,0)):console.error("esri.dijit.Legend: must specify a container for the legend"):console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},postMixInProperties:function(){this.inherited(arguments);var a=["ar","he"],b,c;for(b=0;b<a.length;b+=1)c=a[b],q.locale&&-1!==q.locale.indexOf(c)&&(-1!==q.locale.indexOf("-")?-1!==q.locale.indexOf(c+
"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0);this._isRightToLeft?(this._align=this.alignRight?"left":"right",this._legendAlign=this.alignRight?"esriLegendLeft":"esriLegendRight"):(this._align=this.alignRight?"right":"left",this._legendAlign=this.alignRight?"esriLegendRight":"esriLegendLeft")},startup:function(){this.inherited(arguments);this._initialize();9>h("ie")&&(this._repaintItems=k.hitch(this,this._repaintItems),setTimeout(this._repaintItems,this._ieTimer))},destroy:function(){this._deactivate();
this._removeCachedLegendResponses();this._removeHoverHandlers();this.inherited(arguments)},_removeCachedLegendResponses:function(){this._preserveCacheOnDestroy||f.forEach(this.layers,function(a){delete a.legendResponse})},refresh:function(a){if(this.domNode){a?(this.layerInfos=a,this.layers=[],f.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(this.hideLayersInLegend[a.layer.id]=
a.hideLayers,this._addSubLayersToHide(a)):this.hideLayersInLegend[a.layer.id]=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this)):this.useAllMapLayers&&(this.layers=this.layerInfos=null);for(a=this.domNode.children.length-1;0<=a;a--)d.destroy(this.domNode.children[a]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",_initialize:function(){this.layerInfos&&
(this.layers=[],f.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(this.hideLayersInLegend[a.layer.id]=a.hideLayers,this._addSubLayersToHide(a)):this.hideLayersInLegend[a.layer.id]=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this));this.useAllMapLayers=!1;if(!this.layers){this.useAllMapLayers=
!0;this.layers=[];var a=[],b=[];f.forEach(this.map.layerIds,function(c){c=this.map.getLayer(c);var g;this._isSupportedLayerType(c)&&(c.arcgisProps&&c.arcgisProps.title&&(c._titleForLegend=c.arcgisProps.title),this.layers.push(c));"esri.layers.KMLLayer"==c.declaredClass&&(g=c.getLayers(),f.forEach(g,function(b){a.push(b.id)},this));"esri.layers.GeoRSSLayer"==c.declaredClass&&(g=c.getFeatureLayers(),f.forEach(g,function(a){b.push(a.id)},this))},this);f.forEach(this.map.graphicsLayerIds,function(c){var g=
this.map.getLayer(c);-1==f.indexOf(a,c)&&-1==f.indexOf(b,c)&&this._isSupportedLayerType(g)&&this._isLayerDrawingEnabled(g)&&(g.arcgisProps&&g.arcgisProps.title&&(g._titleForLegend=g.arcgisProps.title),this.layers.push(g))},this)}this._createLegend()},_isLayerDrawingEnabled:function(a){return a&&(a._params&&a._params.drawMode||a.isFeatureReductionActive&&a.isFeatureReductionActive())},_activate:function(){this._deactivate();this.autoUpdate&&(this._respectCurrentMapScale&&(this._ozeConnect=l.connect(this.map,
"onZoomEnd",this,"_refreshLayers")),this.useAllMapLayers&&(this._olaConnect=l.connect(this.map,"onLayerAdd",this,"_updateAllMapLayers"),this._olrConnect=l.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=l.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers")),f.forEach(this.layers,function(a){var b={};b.oarcConnect=l.connect(a,"onFeatureReductionRendererChange",this,"_refreshLayers");b.oaicConnect=l.connect(a,"onFeatureReductionChange",this,"_refreshLayers");
b.ovcConnect=l.connect(a,"onVisibilityChange",this,"_refreshLayers");b.oocConnect=l.connect(a,"onOpacityChange",this,"_refreshLayers");b.oscConnect=l.connect(a,"onScaleRangeChange",this,"_refreshLayers");"esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass&&a.supportsDynamicLayers&&(b.odcConnect=l.connect(a,"_onDynamicLayersChange",k.hitch(this,"_updateDynamicLayers",a)));"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&(b.oirConnect=l.connect(a,"onRenderingChange",k.partial(this._updateImageServiceLayers,
this,a)),b.oivrConnect=l.connect(a,"onRendererChange",k.partial(this._updateImageServiceLayers,this,a)));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&(b.oivrConnect=l.connect(a,"onRendererChange",k.hitch(this,"_refreshLayers")));this.layerConnects[a.id]=b},this))},_deactivate:function(){this._ozeConnect&&l.disconnect(this._ozeConnect);this._olaConnect&&l.disconnect(this._olaConnect);this._olroConnect&&l.disconnect(this._olroConnect);this._olrConnect&&l.disconnect(this._olrConnect);
f.forEach(this.layers,function(a){a=this.layerConnects[a.id]||{};a.oarcConnect&&l.disconnect(a.oarcConnect);a.oaicConnect&&l.disconnect(a.oaicConnect);a.ovcConnect&&l.disconnect(a.ovcConnect);a.oocConnect&&l.disconnect(a.oocConnect);a.oscConnect&&l.disconnect(a.oscConnect);a.odcConnect&&l.disconnect(a.odcConnect);a.oirConnect&&l.disconnect(a.oirConnect);a.oivrConnect&&l.disconnect(a.oivrConnect)},this);this.layerConnects=[]},_updateDynamicLayers:function(a){delete a.legendResponse;this._refreshLayers()},
_updateImageServiceLayers:function(a,b){delete b.legendResponse;a._refreshLayers()},_refreshLayers:function(){this.refresh()},_updateAllMapLayers:function(){this.layers=[];f.forEach(this.map.layerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&this.layers.push(a)},this);f.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&this._isLayerDrawingEnabled(a)&&this.layers.push(a)},this);this.refresh()},_createLegend:function(){var a=
!1,b=!1;w.set(this.domNode,"position","relative");d.create("div",{id:this.id+"_msg",className:"esriLegendMsg",innerHTML:this.NLS_creatingLegend+"..."},this.domNode);var c=[];f.forEach(this.layers,function(e){if("esri.layers.KMLLayer"==e.declaredClass||"esri.layers.GeoRSSLayer"==e.declaredClass){var g;e.loaded?("esri.layers.KMLLayer"==e.declaredClass?g=e.getLayers():"esri.layers.GeoRSSLayer"==e.declaredClass&&(g=e.getFeatureLayers(),this.hideLayersInLegend[e.id]&&(g=f.filter(g,function(a){return-1==
f.indexOf(this.hideLayersInLegend[e.id],a.id)},this))),f.forEach(g,function(a){"esri.layers.FeatureLayer"==a.declaredClass&&e._titleForLegend&&(a._titleForLegend=e._titleForLegend+" - ","esriGeometryPoint"==a.geometryType?a._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==a.geometryType?a._titleForLegend+=this.NLS_lines:"esriGeometryPolygon"==a.geometryType&&(a._titleForLegend+=this.NLS_areas),c.push(a))},this)):l.connect(e,"onLoad",k.hitch(this,function(){this.refresh(this.layerInfos)}))}else if("esri.layers.WMSLayer"===
e.declaredClass)if(!e.loaded)l.connect(e,"onLoad",k.hitch(this,function(){this.refresh(this.layerInfos)}));else{if((!this._respectVisibility||this._respectVisibility&&e.visible)&&0<e.layerInfos.length&&f.some(e.layerInfos,function(a){return a.legendURL})){var C=!1;f.forEach(e.layerInfos,function(b){if(b.legendURL&&-1<f.indexOf(e.visibleLayers,b.name)){C||(d.create("div",{innerHTML:"\x3cspan class\x3d'esriLegendServiceLabel'\x3e"+(e._titleForLegend||e.name||e.id)+"\x3c/span\x3e"},this.domNode),C=!0);
var c;b=b.legendURL;if(e.customParameters||e.customLayerParameters){var g=k.clone(e.customParameters||{});k.mixin(g,e.customLayerParameters||{});for(c in g)b+=(-1===b.indexOf("?")?"?":"\x26")+c+"\x3d"+g[c]}d.create("div",{innerHTML:"\x3cimg src\x3d'"+b+"'/\x3e"},this.domNode);a=!0}},this)}}else"esri.layers.WFSLayer"!==e.declaredClass||e.renderer?c.push(e):(g=d.create("div",{id:this.id+"_"+e.id,"class":"esriLegendService"}),d.create("span",{innerHTML:this._getServiceTitle(e),"class":"esriLegendServiceLabel"},
d.create("td",{align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},g))))),d.place(g,this.id,"first"),g=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g),g=d.create("tbody",{},g),"esriGeometryComplex"===e.geometryType?(this._buildRow_Renderer(e,e._pointSymbol,null,this.NLS_points,null,g),this._buildRow_Renderer(e,e._lineSymbol,null,this.NLS_lines,null,g),this._buildRow_Renderer(e,e._polygonSymbol,null,this.NLS_areas,null,g)):
"esriGeometryPoint"===e.geometryType?this._buildRow_Renderer(e,e._pointSymbol,null,"",null,g):"esriGeometryPolyline"===e.geometryType?this._buildRow_Renderer(e,e._lineSymbol,null,"",null,g):"esriGeometryPolygon"===e.geometryType&&this._buildRow_Renderer(e,e._polygonSymbol,null,"",null,g),b=!0)},this);var g=[];f.forEach(c,function(a){if(!a.loaded)var b=l.connect(a,"onLoad",this,function(a){l.disconnect(b);b=null;this.refresh()});else if((!this._respectVisibility||this._respectVisibility&&a.visible)&&
(a.layerInfos||a.renderer||"esri.layers.ArcGISImageServiceLayer"==a.declaredClass)){var c=d.create("div",{id:this.id+"_"+a.id,style:{display:"none"},"class":"esriLegendService"});d.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},d.create("td",{align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},c)))));d.place(c,this.id,"first");a.legendResponse||a.renderer&&"esri.renderer.StretchRenderer"!==a.renderer.declaredClass?this._createLegendForLayer(a):
this.isHostedTileService(a)?this._getLayerInfos(a).then(k.hitch(this,function(a){this._createLegendForLayer(a)}),k.hitch(this,function(a){g.push(this._legendRequest(a))})):g.push(this._legendRequest(a))}},this);0!==g.length||a||b?(new I(g)).addCallback(k.hitch(this,function(c){a||b?v.byId(this.id+"_msg").innerHTML="":v.byId(this.id+"_msg").innerHTML=this.NLS_noLegend;this._activate()})):(v.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate())},_createLegendForLayer:function(a){if(a.legendResponse||
a.renderer||this.isHostedTileService(a)){var b=!1;if(a.legendResponse||this.isHostedTileService(a)){var c=a.dynamicLayerInfos||a.layerInfos;c&&c.length?f.forEach(c,function(c,e){if(!this.hideLayersInLegend[a.id]||-1===f.indexOf(this.hideLayersInLegend[a.id],c.id)){var g=this._buildLegendItems(a,c,e);b=b||g}},this):"esri.layers.ArcGISImageServiceLayer"==a.declaredClass&&(b=this._buildLegendItems(a,{id:0,name:null,title:a.name,subLayerIds:null,parentLayerId:-1},0))}else a.renderer&&(c=a.url?a.url.substring(a.url.lastIndexOf("/")+
1,a.url.length):"fc_"+a.id,b=this._buildLegendItems(a,{id:c,name:null,subLayerIds:null,parentLayerId:-1},0));b&&(w.set(v.byId(this.id+"_"+a.id),"display","block"),w.set(v.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(a){if(a.loaded)return 10.01<=a.version?this._legendRequestServer(a):this._legendRequestTools(a);l.connect(a,"onLoad",k.hitch(this,"_legendRequest"))},_legendRequestServer:function(a){var b=a.url,c=b.indexOf("?"),b=-1<c?b.substring(0,c)+"/legend"+b.substring(c):b+"/legend";
(c=a._getToken())&&(b+="?token\x3d"+c);var g=k.hitch(this,"_processLegendResponse"),e={f:"json"};a._params.dynamicLayers&&(e.dynamicLayers=K.stringify(this._createDynamicLayers(a)),"[{}]"===e.dynamicLayers&&(e.dynamicLayers="[]"));a._params.bandIds&&(e.bandIds=a._params.bandIds);a._params.renderingRule?e.renderingRule=a._params.renderingRule:a.rasterFunctionInfos&&0<a.rasterFunctionInfos.length&&f.forEach(a.rasterFunctionInfos,function(a){a&&a.name&&"none"===a.name.toLowerCase()&&(e.renderingRule=
K.stringify({rasterFunction:a.name}))});return P({url:b,content:e,callbackParamName:"callback",load:function(b,c){g(a,b,c)},error:Q.defaults.io.errorHandler})},_legendRequestTools:function(a){var b=a.url.toLowerCase().indexOf("/rest/"),b=a.url.substring(0,b)+a.url.substring(b+5,a.url.length),b=this._legendUrl+"?soapUrl\x3d"+window.escape(b);if(!h("ie")||8<h("ie"))b+="\x26returnbytes\x3dtrue";var c=k.hitch(this,"_processLegendResponse");return P({url:b,content:{f:"json"},callbackParamName:"callback",
load:function(b,e){c(a,b,e)},error:Q.defaults.io.errorHandler})},_processLegendResponse:function(a,b){b&&b.layers?(a.legendResponse=b,v.byId(this.id+"_"+a.id)&&d.empty(v.byId(this.id+"_"+a.id)),d.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},d.create("td",{align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},v.byId(this.id+"_"+a.id)))))),this._createLegendForLayer(a)):console.log("Legend could not get generated for "+a.url+": "+
A.toJson(b))},_buildLegendItems:function(a,b,c){var g=!1,e=v.byId(this.id+"_"+a.id),p=b.parentLayerId;if(b.subLayerIds)a=d.create("div",{id:this.id+"_"+a.id+"_"+b.id+"_group",style:{display:"none"},"class":-1==p?0<c?"esriLegendGroupLayer":"":this._legendAlign},-1==p?e:v.byId(this.id+"_"+a.id+"_"+p+"_group")),d.create("td",{innerHTML:x.encode(b.name),align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%","class":"esriLegendLayerLabel"},a))));else{if(this._respectVisibility&&
a.visibleLayers)if(c=a.dynamicLayerInfos||a.layerInfos)if(a._params&&a._params.layers){if(-1===f.indexOf(a.visibleLayers,b.id))return g}else{if(c=this._getReallyVisibleLayers(c,a.visibleLayers),-1===f.indexOf(c,b.id))return g}else if(-1===f.indexOf(a.visibleLayers,b.id))return g;e=d.create("div",{id:this.id+"_"+a.id+"_"+b.id,style:{display:"none"},"class":-1<p?this._legendAlign:""},-1==p?e:v.byId(this.id+"_"+a.id+"_"+p+"_group"));d.create("td",{innerHTML:x.encode(b.name)||"",align:this._align},d.create("tr",
{},d.create("tbody",{},d.create("table",{width:"95%","class":"esriLegendLayerLabel"},e))));c=a.dynamicLayerInfos||a.layerInfos;p=!1;c&&c.length&&(p=f.some(c,function(a){return!!a.drawingInfo}));if(a.legendResponse)g=g||this._buildLegendItems_Tools(a,b,e);else if(a.renderer||p)g=g||this._buildLegendItems_Renderer(a,b,e)}return g},_getReallyVisibleLayers:function(a,b){if(!a||!b||!b.length)return[];var c=[],g=[],e;for(e=0;e<a.length;e++)if(a[e].subLayerIds){if(-1===f.indexOf(b,a[e].id)||-1<f.indexOf(g,
a[e].id))g=g.concat(a[e].subLayerIds)}else-1<f.indexOf(b,a[e].id)&&-1===f.indexOf(g,a[e].id)&&c.push(a[e].id);return c},_buildLegendItems_Tools:function(a,b,c){var g=b.parentLayerId,e=this.map.getScale(),p=!1,C=function(a,b){var c,e;for(c=0;c<a.length;c++)if(b.dynamicLayerInfos)for(e=0;e<b.dynamicLayerInfos[e].length;e++){if(b.dynamicLayerInfos[e].mapLayerId==a[c].layerId)return a[c]}else if(b.id==a[c].layerId)return a[c];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&this._isLayerInScale(a,
b,e)){var h=!0;if(this._respectCurrentMapScale&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISMapServiceLayer"===a.declaredClass)){var u=this._getEffectiveScale(a,b);if(u.minScale&&u.minScale<e||u.maxScale&&u.maxScale>e)h=!1}if(h){var e=C(a.legendResponse.layers,b),k=e.legendType,m=e.layerType,l=e.legend;if(l){"esri.layers.ArcGISImageServiceLayer"!==a.declaredClass&&this._sanitizeLegendResponse(a,e,b);c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%",
"class":"esriLegendLayer"},c);var n=d.create("tbody",{},c);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b);var t=[];f.forEach(l,function(c){if(!(10.1<=a.version&&!c.values&&1<l.length)||!a._hideDefaultSymbol&&"\x3call other values\x3e"!==c.label&&(c.label||"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.3<=a.version||"Raster Layer"===m)){var e=c.label;if(c.url&&0===c.url.indexOf("http")||c.imageData&&0<c.imageData.length)p=!0,e&&-1!==f.indexOf(t,e)||(t.push(e),this._buildRow_Tools(c,
n,a,b.id,k))}},this)}}}p&&(w.set(v.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<g&&(w.set(v.byId(this.id+"_"+a.id+"_"+g+"_group"),"display","block"),this._findParentGroup(a.id,a,g)));return p},_getLayerInfos:function(a){var b=new D,c=a.dynamicLayerInfos||a.layerInfos;if(c&&c.length)if(f.some(c,function(a){return!!a.drawingInfo}))b.resolve(a);else{var g=a.url,e=g.indexOf("?"),g=-1==e?g+"/layers":g.substring(0,e)+"/layers"+g.substring(e,g.length);P({url:g,content:{f:"json"},callbackParamName:"callback",
load:function(e,g){e.layers?(f.forEach(c,function(a){var b=f.filter(e.layers,function(b){return a.source?b.id===a.source.mapLayerId:b.id===a.id});b&&b[0]&&b[0].drawingInfo&&(a.drawingInfo=b[0].drawingInfo,a.fields=b[0].fields)}),b.resolve(a)):b.reject(a)},error:function(c){b.reject(a)}})}return b},_sanitizeLegendResponse:function(a,b,c){var g=b.legend;if(10.1<=a.version&&1<g.length&&!b._sanitized){a=k.getObject("layerDefinition.drawingInfo.renderer",!1,c);var e,d;a||(a=k.getObject("drawingInfo.renderer",
!1,c));f.some(g,function(a){if(a.values)return!0})&&f.some(g,function(a,b){a.values||(d=b,e=a);return!!e});a?"uniqueValue"===a.type?e&&(g.splice(d,1),g.push(e)):"classBreaks"===a.type&&(e&&g.splice(d,1),g.reverse(),e&&g.push(e)):e&&(g.splice(d,1),g.push(e));b._sanitized=!0}},_buildRow_Tools:function(a,b,c,g,e){var f=d.create("tr",{},b),C;this.alignRight?(b=d.create("td",{align:this._isRightToLeft?"left":"right"},f),C=d.create("td",{align:this._isRightToLeft?"left":"right",width:35},f)):(C=d.create("td",
{width:35,align:"center"},f),b=d.create("td",{},f));f=a.url;(!h("ie")||9<=h("ie")||9>h("ie")&&"esri.layers.ArcGISImageServiceLayer"===c.declaredClass)&&a.imageData&&0<a.imageData.length?f="data:image/png;base64,"+a.imageData:0!==a.url.indexOf("http")&&(f=c.url+"/"+g+"/images/"+a.url,(g=c._getToken())&&(f+="?token\x3d"+g));g=d.create("img",{src:f,border:0,style:"opacity:"+c.opacity},C);a=d.create("td",{innerHTML:x.encode(a.label),align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",
{width:"95%",dir:"ltr"},b))));e&&"Stretched"===e&&10.3<=c.version&&"esri.layers.ArcGISImageServiceLayer"===c.declaredClass&&(a.style.verticalAlign="top",a.style.lineHeight="1",g.style.marginBottom="-1px",g.style.display="block",b.style.verticalAlign="top");9>h("ie")&&(g.style.filter="alpha(opacity\x3d"+100*c.opacity+")")},_getVariable:function(a,b,c){var g;a&&(g=(a=a.getVisualVariablesForType(b,c))&&a[0]);return g},_getVariables:function(a,b,c){a=[this._getVariable(a,"colorInfo",!1),this._getVariable(a,
"opacityInfo",!1),this._getVariable(a,"sizeInfo",!1)];return b?f.filter(a,function(a){return!(!a||a.field!==b||a.normalizationField!=c)}):a},_getFieldAlias:function(a,b,c){var g=b.infoTemplate||(b.infoTemplates&&c&&b.infoTemplates[c.id]?b.infoTemplates[c.id].infoTemplate:null),g=g&&g.getFieldInfo&&g.getFieldInfo(a);a=k.isFunction(a)?null:this.getField(b,a,c);b=g||a;c="";b&&(c=g&&g.label||a&&a.alias||b.name||b.fieldName);return c},_getDomainName:function(a,b,c,g){var e;a&&!k.isFunction(a)&&(e=(c=(a=
this.getField(c,a,g))&&c.getDomain?c.getDomain(a.name):null)&&c.codedValues?c.getName(b):null);return e},_getRampTitle:function(a,b,c){var g,e=a.field,d=a.normalizationField,f=!1,h=!1,u=!1,e=k.isFunction(e)?null:e,d=k.isFunction(d)?null:d;if(a.legendOptions&&a.legendOptions.title)g=a.legendOptions.title;else if(a.valueExpressionTitle)g=a.valueExpressionTitle;else{if(b.renderer&&b.renderer.authoringInfo&&b.renderer.authoringInfo.visualVariables){var B=b.renderer.authoringInfo.visualVariables;for(a=
0;a<B.length;a++){var m=B[a];if("colorInfo"===m.type&&"ratio"===m.style){f=!0;break}else if("colorInfo"===m.type&&"percent"===m.style){h=!0;break}else if("colorInfo"===m.type&&"percentTotal"===m.style){u=!0;break}}}(f=u&&"showRatioPercentTotal"||h&&"showRatioPercent"||f&&"showRatio"||d&&"showNormField"||e&&"showField"||null)&&(g=J.substitute({field:e&&this._getFieldAlias(e,b,c),normField:d&&this._getFieldAlias(d,b,c)},this._i18n[f]))}return g},_getRendererTitle:function(a,b,c){var g;if(a){var e,d,
f;"esri.renderer.ClassBreaksRenderer"===a.declaredClass&&(e=a.attributeField,d=a.normalizationField,f="percent-of-total"===a.normalizationType);e=k.isFunction(e)?null:e;d=k.isFunction(d)?null:d;a.legendOptions&&a.legendOptions.title?g=a.legendOptions.title:a.valueExpressionTitle?g=a.valueExpressionTitle:(a=d&&"showNormField"||(f?"showNormPct":null)||e&&"showField"||null)&&(g=J.substitute({field:e&&this._getFieldAlias(e,b,c),normField:d&&this._getFieldAlias(d,b,c)},this._i18n[a]))}return g},_buildLegendItems_Renderer:function(a,
b,c){var g=b.parentLayerId,e=this.map,p=e.getScale(),C,h=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(a,b,p)){var u,B,m,l,n,t,r,q;m="esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass?a.renderer.renderer:b&&b.drawingInfo?W.fromJson(k.clone(b.drawingInfo.renderer)):a.isFeatureReductionActive&&a.isFeatureReductionActive()?a.getFeatureReductionRenderer():a.renderer;if("esri.renderer.ScaleDependentRenderer"===m.declaredClass&&(m=(e="zoom"===m.rangeType?m.getRendererInfoByZoom(e.getZoom()):
m.getRendererInfoByScale(p))&&e.renderer,!m))return!1;var E=this._getVariables(m),y=f.filter(E,function(a){return!!a}).length,p=E[0],e=E[1],E=E[2],z,A,D,F,G;p&&(l=this._getMedianColor(m,p),p.field&&(t=k.isFunction(p.field)?null:this.getField(a,p.field,b)),z=!(p.legendOptions&&!1===p.legendOptions.showLegend));e&&(e.field&&(q=k.isFunction(e.field)?null:this.getField(a,e.field,b)),A=!(e.legendOptions&&!1===e.legendOptions.showLegend));E&&(E.field&&(r=k.isFunction(E.field)?null:this.getField(a,E.field,
b)),D=!(E.legendOptions&&!1===E.legendOptions.showLegend));if("esri.renderer.HeatmapRenderer"===m.declaredClass)C=h=!0,this._showHeatRamp(a,b,m,c);else if("esri.renderer.DotDensityRenderer"===m.declaredClass)C=h=!0,this._showDotDensityLegend(a,b,m,c);else if("esri.renderer.TemporalRenderer"===m.declaredClass)C=h=!0,B=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),u=d.create("tbody",{},B),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(B,a,b),m.latestObservationRenderer&&
"esri.renderer.SimpleRenderer"===m.latestObservationRenderer.declaredClass&&this._buildRow_Renderer(a,m.latestObservationRenderer.symbol,l,x.encode(m.latestObservationRenderer.label)||this.NLS_currentObservations,null,u),m.observationRenderer&&"esri.renderer.SimpleRenderer"===m.observationRenderer.declaredClass&&this._buildRow_Renderer(a,m.observationRenderer.symbol,l,x.encode(m.observationRenderer.label)||this.NLS_previousObservations,null,u);else if("esri.renderer.UniqueValueRenderer"===m.declaredClass){if(m.infos&&
0<m.infos.length){C=h=!0;if(m.legendOptions&&m.legendOptions.title||m.valueExpressionTitle)B=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),u=d.create("tbody",{},B),y=m.legendOptions&&m.legendOptions.title?m.legendOptions.title:m.valueExpressionTitle,this._buildRow_Renderer(a,null,l,x.encode(y),null,u);B=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c);u=d.create("tbody",{},B);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(B,
a,b);m.attributeField&&E&&this._addSubHeader(u,this._getFieldAlias(m.attributeField,a,b));var H=[];f.forEach(m.infos,function(c){var e=null;a._editable&&a.types&&(e=this._getTemplateFromTypes(a.types,c.value));var g=c.label;null==g&&(g=this._getDomainName(m.attributeField,c.value,a,b)||c.value);-1===f.indexOf(H,g)&&(H.push(g),this._buildRow_Renderer(a,c.symbol,l,x.encode(g),e,u))},this)}G=this._displayDefaultSymbol(a,m,c)}else if("esri.renderer.ClassBreaksRenderer"===m.declaredClass){if(m.infos&&
0<m.infos.length||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass)C=h=!0,F=this._isUnclassedRenderer(m),p||1!==m.infos.length||(n=(n=m.infos[0])&&n.symbol),F||(B=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),u=d.create("tbody",{},B),y=this._getRendererTitle(m,a,b),this._buildRow_Renderer(a,null,l,x.encode(y),null,u)),B=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),u=d.create("tbody",{},B),(a._hoverLabel||
a._hoverLabels)&&this._createHoverAction(B,a,b),F&&E&&D||(y=m.infos.slice(0).reverse(),f.forEach(y,function(b){var c=b.label;null!=c||F||(c=b.minValue+" - "+b.maxValue);this._buildRow_Renderer(a,b.symbol,l,x.encode(c),null,u)},this)),"esri.layers.ArcGISImageServiceVectorLayer"!==a.declaredClass||a.renderer.style!==R.STYLE_SCALAR&&a.renderer.style!==R.STYLE_SINGLE_ARROW||(this._buildRow_Renderer(a,m.defaultSymbol,null,"",null,u),a._hideDefaultSymbol=!0);F||(G=this._displayDefaultSymbol(a,m,c))}else"esri.renderer.SimpleRenderer"===
m.declaredClass&&(C=h=!0,B=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),u=d.create("tbody",{},B),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(B,a,b),n=null,a._editable&&a.templates&&0<a.templates.length&&(n=a.templates[0]),B=1<y?null:t&&z||q&&A||r&&D,this._buildRow_Renderer(a,m.symbol,l,x.encode(B?this._getRampTitle(1<y?null:p||e||E,a,b):m.label),n,u),n=p?null:m.symbol,B&&(t=q=r=null));C&&(p&&z&&(p.field||p.valueExpression)&&this._showGradientRamp(a,
b,m,null,c,p,t,null,E&&D?!0:!1),E&&D&&(E.field||E.valueExpression)&&(C=p&&z||"esri.renderer.UniqueValueRenderer"===m.declaredClass?!1:!0,this._showSizeLegend(a,b,m,E,l,c,r,null,C)),e&&A&&(e.field||e.valueExpression)&&this._showGradientRamp(a,b,m,n&&!n.url&&n.color?n.color:this.transparencyRampColor,c,e,q,null,!1));G||F&&!z&&!D&&!A||(G=this._displayDefaultSymbol(a,m,c));h=h||G}h&&(w.set(v.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<g&&(w.set(v.byId(this.id+"_"+a.id+"_"+g+"_group"),"display",
"block"),this._findParentGroup(a.id,g)));return h},_isUnclassedRenderer:function(a,b){var c;if("esri.renderer.ClassBreaksRenderer"===a.declaredClass&&a.infos&&1===a.infos.length){c=a.attributeField;var g=a.normalizationField;c=b?c===b:!!this._getVariables(a,c,g).length}return c},_displayDefaultSymbol:function(a,b,c){var g;!a._hideDefaultSymbol&&b.defaultSymbol&&(g=!0,c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),c=d.create("tbody",{},c),this._buildRow_Renderer(a,
b.defaultSymbol,null,x.encode(b.defaultLabel)||"others",null,c));return g},_showGradientRamp:function(a,b,c,g,e,f,h,l,u){u=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(u?"":" esriLegendSubFragment")},e);e=d.create("tbody",{},u);(a._hoverLabel||a._hoverLabels||l)&&this._createHoverAction(u,a,b,l);(h||f.valueExpression||f.legendOptions&&f.legendOptions.title)&&this._addSubHeader(e,this._getRampTitle(f,a,b));h=f.field;var p;h&&(p=k.isFunction(h)?null:this.getField(a,
h,b));(b=this._getRampStops(c,f,g,p&&"esriFieldTypeDate"===p.type))&&b.length&&this._drawGradientRamp(e,b,!0,a,this._getRampBorderColor(c),!!g)},_getMedianColor:function(a,b){var c,g;b.colors?(c=b.minDataValue,g=b.maxDataValue):b.stops&&(c=b.stops[0].value,g=b.stops[b.stops.length-1].value);return a.getColor(c+(g-c)/2,{colorInfo:b})},_getRampStops:function(a,b,c,g){var e,d,h,k,u=!1;b.colors||b.opacityValues?(d=b.maxDataValue-b.minDataValue,e=f.map([0,.25,.5,.75,1],function(a){h=b.minDataValue+a*d;
return Number(h.toFixed(6))}),this._checkPrecision(0,4,e)):b.stops&&(e=f.map(b.stops,function(a){return a.value}),(u=f.some(b.stops,function(a){return!!a.label}))&&(k=f.map(b.stops,function(a){return a.label})));var l=e[0],m,n;d=e[e.length-1]-l;return f.map(e,function(f,h){c?(m=new z(c.toRgba()),n=a.getOpacity(f,{opacityInfo:b}),null!=n&&(m.a=n)):m=a.getColor(f,{colorInfo:b});var p="";if(u)p=k[h];else{var p=g?M.formatDate(f,M.timelineDateFormatOptions):F.format(f),C="";0===h?C=this._specialChars.lt+
" ":h===e.length-1&&(C=this._specialChars.gt+" ");p=C+p}return{value:f,color:m,offset:1-(f-l)/d,label:p}},this).reverse()},_checkPrecision:function(a,b,c){var g=a+(b-a)/2,e=c[a],d=c[g],f=c[b],h=Math.floor(e),k=Math.floor(d),l=Math.floor(f);h===e&&l===f&&k!==d&&h!==k&&l!==k&&(c[g]=k);a+1!==g&&this._checkPrecision(a,g,c);g+1!==b&&this._checkPrecision(g,b,c)},_getRampBorderColor:function(a){var b;if("esri.renderer.SimpleRenderer"===a.declaredClass)b=a.symbol;else if("esri.renderer.UniqueValueRenderer"===
a.declaredClass||"esri.renderer.ClassBreaksRenderer"===a.declaredClass)b=a.infos[0].symbol;return(a=b&&-1===b.type.indexOf("linesymbol")?b.getStroke():null)&&a.color},_drawGradientRamp:function(a,b,c,g,e,p){var k=d.create("tr",{},a),l,u,n,m,t,r=b.length-1,q;m=0;this.alignRight?(a=d.create("td",{align:this._isRightToLeft?"left":"right"},k),l=d.create("td",{align:this._isRightToLeft?"left":"right",width:this.gradientWidth},k)):(l=d.create("td",{width:this.gradientWidth,align:"center"},k),a=d.create("td",
{},k));k=e&&0<e.a&&!(240<=e.r&&240<=e.g&&240<=e.b);u=d.create("div",{"class":k?"":"esriLegendBorderLessColorRamp",style:"position: relative; width:"+this.gradientWidth+"px;"},l);l=d.create("div",{"class":"esriLegendColorRamp"+(p?" esriLegendTransparencyRamp":"")},u);p=w.get(l,"width");k&&(e=9>h("ie")?e.toHex():"rgba("+e.toRgba().join(",")+")",w.set(l,"border",this.colorRampBorder+" "+e));c?(e=this.gradientHeight*r,w.set(l,"height",e+"px")):e=w.get(l,"height");w.set(u,"height",e+"px");k=L.createSurface(l,
p,e);9>h("ie")&&(m=k.getEventSource(),w.set(m,"position","relative"),w.set(m.parentNode,"position","relative"),m=1);try{c&&f.forEach(b,function(a,b){a.offset=b/r}),t=k.createRect({x:-m,y:-m,width:p+m,height:e+m}),t.setFill({type:"linear",x1:0,y1:0,x2:0,y2:e,colors:b}).setStroke(null),k.createRect({width:p,height:e}).setFill(new z([255,255,255,1-g.opacity])).setStroke(null),this._surfaceItems.push(k)}catch(fa){k.clear(),k.destroy()}f.forEach(b,function(a,c){if(a.label){q="top:"+100*a.offset+"%;";var e=
"";0===c&&(e+=" esriLegendColorRampTickFirst");c===b.length-1&&(e+=" esriLegendColorRampTickLast");d.create("div",{"class":"esriLegendColorRampTick"+e,innerHTML:"\x26nbsp;",style:q},u)}});n=d.create("div",{"class":"esriLegendColorRampLabels",style:{height:e+this.gradientHeight+"px"}},a);c?f.forEach(b,function(a){d.create("div",{"class":"esriLegendColorRampLabel",innerHTML:x.encode(a.label)||"\x26nbsp;"},n)}):(d.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.high},n),d.create("div",
{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.low,style:"top: "+(e+this.gradientHeight-2*this.gradientHeight)+"px;"},n))},_showHeatRamp:function(a,b,c,g,e){var f,h=c.field;f=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g);g=d.create("tbody",{},f);(a._hoverLabel||a._hoverLabels||e)&&this._createHoverAction(f,a,b,e);(h=h&&this.getField(a,h,b))&&this._addSubHeader(g,this._getFieldAlias(h.name,a,b));b=this._getHeatmapStops(c);b.length&&this._drawGradientRamp(g,
b,!1,a)},_getHeatmapStops:function(a){var b=a.colorStops;a=a.colors;var c,g,e,d;b&&b[0]?(c=b.length-1,(a=b[0]&&null!=b[0].ratio)?(a=b[c])&&1!==a.ratio&&(b=b.slice(0),b.push({ratio:1,color:a.color}),c++):(g=b[0].value,e=b[c].value-g,b=f.map(b,function(a){return{color:a.color,ratio:(a.value-g)/e}}))):a&&a[0]&&(c=a.length-1,d=1/(a.length-1),b=f.map(a,function(a,b){return{color:a,ratio:b*d}}));b=f.map(b,function(a,b){var e="";0===b?e="Low":b===c&&(e="High");return{color:a.color,label:e,offset:1-a.ratio}});
return b.reverse()},_showDotDensityLegend:function(a,b,c,g){var e=c.legendOptions,h,l,n,u,B,m,t,r=this.dotDensitySwatchSize,q=Math.round(r/2);e&&(l=e.backgroundColor,n=e.outline,u=e.valueUnit,B=e.dotCoverage);B=(B||this.dotCoverage)/100;t=Math.round(r*r/Math.pow(c.dotSize,2)*B);g=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g);m=d.create("tbody",{},g);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(g,a,b);this._addSubHeader(m,J.substitute({value:c.dotValue,
unit:u||""},this.NLS_dotValue));f.forEach(c.fields,function(e){e=k.mixin({},e);e.numPoints=t;h=new U(c._generateImageSrc(r,r,[e],{x:0,y:0},{x:r,y:r},l),n||c.outline,r,r);e=this.getField(a,e.name,b)||e;this._buildRow_Renderer(a,h,null,x.encode(this._getFieldAlias(e.name,a,b)),null,m,{type:"path",path:"M "+-q+","+-q+" L "+q+","+-q+" L "+q+","+q+" L "+-q+","+q+" L "+-q+","+-q+" E"})},this)},_showSizeLegend:function(a,b,c,g,e,f,h,l,u){var p=g.legendOptions,p=p&&p.customValues;e=this._getSizeSymbol(c,
e);if((!g.valueUnit||"unknown"===g.valueUnit)&&e&&(p||null!=g.minSize&&null!=g.maxSize&&null!=g.minDataValue&&null!=g.maxDataValue||g.stops&&!(1>=g.stops.length))){u=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(u?"":" esriLegendSubFragment")},f);f=d.create("tbody",{},u);(a._hoverLabel||a._hoverLabels||l)&&this._createHoverAction(u,a,b,l);(h||g.valueExpression||g.legendOptions&&g.legendOptions.title)&&this._addSubHeader(f,this._getRampTitle(g,a,b));h=g.field;
var m;l=k.isFunction(h);h&&(m=l?null:a.isFeatureReductionActive&&a.isFeatureReductionActive()?a.getFeatureReductionField(h):this.getField(a,h,b));b=m&&"esriFieldTypeDate"===m.type;var p=p||this._getDataValues(c,e,g,b),n,C=p.length-1;for(m=C;0<=m;m--)u=p[m],e=N.fromJson(e.toJson()),this._applySize(e,c,g,u),u=b?M.formatDate(u,M.timelineDateFormatOptions):F.format(u),n="",m===C?n=this._specialChars.gt+" ":0===m&&(n=h&&!l&&"cluster_count"===h.toLowerCase()&&1===p[m]?"":this._specialChars.lt+" "),n="\x3cspan class\x3d'esriLegendSizeRampLabel'\x3e"+
x.encode(n+u)+"\x3c/span\x3e",this._buildRow_Renderer(a,e,null,n,null,f)}},_getSizeSymbol:function(a,b){var c,g;if("esri.renderer.SimpleRenderer"===a.declaredClass)c=a.symbol;else if("esri.renderer.VectorFieldRenderer"===a.declaredClass)c=a.defaultSymbol;else if("esri.renderer.UniqueValueRenderer"===a.declaredClass||"esri.renderer.ClassBreaksRenderer"===a.declaredClass)c=a.infos[0].symbol,g=1<a.infos.length;if(c=c&&-1!==c.type.indexOf("fillsymbol")?null:c)if(c=N.fromJson(c.toJson()),b||g)-1!==c.type.indexOf("linesymbol")?
c.setColor(new z(this.sizeRampDarkColor)):(c.setColor(new z(this.sizeRampLightColor)),c.setOutline&&(g=new V,g.setColor(new z(this.sizeRampDarkColor)),g.setWidth(1.5),c.setOutline(g)));return c},_getDataValues:function(a,b,c,g,e,d){e=null==e?5:e;d=null==d?20:d;var h=a.getSizeRangeAtScale(c,this.map.getScale());e=this._interpolateSizeRange(h,e);var k=this._getDataRange(c),l=f.map(e,function(a){return this._getDataValueFromSize(a,k,h)},this);if(!g){var p,l=F.round(l);for(g=1;g<l.length-1;g++)if(p=this._roundDataValue(a,
b,c,l[g],l[g-1],d))l[g]=p[0],e[g]=p[1]}return l},_getDataRange:function(a){var b=a.stops;return b?{min:b[0].value,max:b[b.length-1].value}:{min:a.minDataValue,max:a.maxDataValue}},_interpolateSizeRange:function(a,b){var c=a.minSize,d=(a.maxSize-c)/(b-1),e,f=[];for(e=0;e<b;e++)f.push(c+d*e);return f},_getDataValueFromSize:function(a,b,c){var d=c.minSize;c=c.maxSize;var e=b.min;b=b.max;return a<=d?e:a>=c?b:(a-d)/(c-d)*(b-e)+e},_roundDataValue:function(a,b,c,d,e,f){var g=this._getSize(b,a,c,d);e=this._getSize(b,
a,c,e);var h,k=F.getDigits(d),l=k.integer,k=k.fractional,m,p,n,q,r,t,v,y,w,x,z;0<d&&1>d&&(h=Math.pow(10,k),d*=h,l=F.getDigits(d).integer);for(--l;0<=l&&(m=Math.pow(10,l),k=Math.floor(d/m)*m,m*=Math.ceil(d/m),null!=h&&(k/=h,m/=h),p=(k+m)/2,p=F.round([k,p,m],{indexes:[1]})[1],n=this._getSize(b,a,c,k),q=this._getSize(b,a,c,m),r=this._getSize(b,a,c,p),t=F.getPctChange(g,n,e,null),v=F.getPctChange(g,q,e,null),y=F.getPctChange(g,r,e,null),w=t.prev<=f,x=v.prev<=f,w&&x&&(t.prev<=v.prev?(w=!0,x=!1):(x=!0,
w=!1)),w?z=[k,n]:x?z=[m,q]:y.prev<=f&&(z=[p,r]),!z);l--);return z},_applySize:function(a,b,c,d){var e=a.type;b=this._getSize(a,b,c,d);switch(e){case "simplemarkersymbol":a.setSize(b);break;case "picturemarkersymbol":e=a.width;c=a.height;a.setHeight(b);a.setWidth(e/c*b);break;case "simplelinesymbol":case "cartographiclinesymbol":a.setWidth(b);break;case "textsymbol":a.font&&a.font.setSize(b)}},_getSize:function(a,b,c,d){return b.getSize(d,{sizeInfo:c,scale:this.map.getScale(),shape:-1!==a.type.indexOf("markersymbol")?
a.style:null})},_buildRow_Renderer:function(a,b,c,g,e,f,h){var k=d.create("tr",{},f),l;this.alignRight?(f=d.create("td",{align:this._isRightToLeft?"left":"right"},k),b&&(l=d.create("td",{align:this._isRightToLeft?"left":"right",width:35},k))):(b&&(l=d.create("td",{width:35,align:"center"},k)),f=d.create("td",{},k));var p=k=30,m;if(b){if("simplemarkersymbol"==b.type)k=Math.min(Math.max(k,b.size+12),125),p=Math.min(Math.max(p,b.size+12),125);else if("picturemarkersymbol"==b.type)k=Math.min(Math.max(k,
b.width),125),p=Math.min(b.height||p,125);else if("textsymbol"==b.type){var n,q;b.text||(n=b.text,q=!0,b.setText(this.defaultText));k=Math.min(Math.max(k,b.getWidth()+12),125);p=Math.min(Math.max(p,b.getHeight()+12),125);q&&b.setText(n)}m=d.create("div",{style:"width:"+k+"px;height:"+p+"px;"},l)}J.isDefined(g)&&"number"===typeof g&&(g=""+g);d.create("td",{innerHTML:g||"",align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},f))));b&&(a=this._drawSymbol(m,b,c,k,p,e,
a,h),this._surfaceItems.push(a))},_addSubHeader:function(a,b){var c=d.create("tr",{},a),c=d.create("td",{align:this._align,colspan:2},c);d.create("td",{innerHTML:x.encode(b)||"",align:this._align},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},c))))},_drawSymbol:function(a,b,c,d,e,f,l,n){b=N.fromJson(b.toJson());var g=l.opacity;c&&b.setColor(new z(c.toRgba()));if("simplelinesymbol"===b.type||"cartographiclinesymbol"===b.type||"textsymbol"===b.type){if(!b.color)return;c=b.color.toRgba();
c[3]*=g;b.color.setColor(c)}else"simplemarkersymbol"===b.type||"simplefillsymbol"===b.type?(b.color&&(c=b.color.toRgba(),c[3]*=g,b.color.setColor(c)),b.outline&&b.outline.color&&(c=b.outline.color.toRgba(),c[3]*=g,b.outline.color.setColor(c))):"picturemarkersymbol"===b.type&&(a.style.opacity=g,a.style.filter="alpha(opacity\x3d("+100*g+"))");a=L.createSurface(a,d,e);9>h("ie")&&(c=a.getEventSource(),w.set(c,"position","relative"),w.set(c.parentNode,"position","relative"));f=this._getDrawingToolShape(b,
f)||N.getShapeDescriptors(b);var p,g=(c=f.defaultShape)&&"text"===c.type;try{g&&!c.text&&(c.text=this.defaultText),p=a.createShape(n||c).setFill(f.fill).setStroke(f.stroke),g&&p.setFont(f.font)}catch(ga){a.clear();a.destroy();return}var m=p.getBoundingBox();n=m.width;f=m.height;var g=-(m.x+n/2),q=-(m.y+f/2);c=a.getDimensions();g={dx:g+c.width/2,dy:q+c.height/2};if("simplemarkersymbol"===b.type&&"path"===b.style)d=l._getScaleMatrix(m,b.size),p.applyTransform(G.scaleAt(d.xx,d.yy,{x:c.width/2,y:c.height/
2}));else if(n>d||f>e)l=n/d>f/e,d=((l?d:e)-5)/(l?n:f),k.mixin(g,{xx:d,yy:d});p.applyTransform(g);return a},_getDrawingToolShape:function(a,b){var c;switch(b?b.drawingTool||null:null){case "esriFeatureEditToolArrow":c={type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 Z"};break;case "esriFeatureEditToolTriangle":c={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 Z"};break;case "esriFeatureEditToolRectangle":c={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 Z"};
break;case "esriFeatureEditToolCircle":c={type:"circle",cx:0,cy:0,r:10};break;case "esriFeatureEditToolEllipse":c={type:"ellipse",cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:c,fill:a.getFill(),stroke:a.getStroke()}},_repaintItems:function(){f.forEach(this._surfaceItems,function(a){this._repaint(a)},this)},_repaint:function(a){if(a){a.getStroke&&a.setStroke&&a.setStroke(a.getStroke());try{a.getFill&&a.setFill&&a.setFill(a.getFill())}catch(b){}a.children&&k.isArray(a.children)&&
f.forEach(a.children,this._repaint,this)}},_createHoverAction:function(a,b,c,g){if(g=b._hoverLabel||b._hoverLabels&&b._hoverLabels[c.id]||g)g=x.encode(g),b.mouseMoveHandler=b.mouseMoveHandler||{},b.mouseMoveHandler[c.id]=l.connect(a,"onmousemove",k.hitch(this,function(a,b){this.mouseX=b.clientX;this.mouseY=b.clientY;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,w.set(v.byId(this.id+"_hoverLabel"),"display","none"));setTimeout(k.hitch(this,function(a,b,c){if(a==this.mouseX&&b==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=
!0,v.byId(this.id+"_hoverLabel")){var e=v.byId(this.id+"_hoverLabel");e.innerHTML="\x3cspan\x3e"+c+"\x3c/span\x3e";w.set(e,"top",b+"px");w.set(e,"left",a+15+"px");w.set(e,"display","")}else d.create("div",{innerHTML:"\x3cspan\x3e"+c+"\x3c/span\x3e",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:b+"px",left:a+15+"px"}},document.body)},b.clientX,b.clientY,a),500)},g)),b.mouseOutHandler=b.mouseOutHandler||{},b.mouseOutHandler[c.id]=l.connect(a,"onmouseout",k.hitch(this,function(a){this.mouseY=
this.mouseX=-1;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,w.set(v.byId(this.id+"_hoverLabel"),"display","none"))}))},_removeHoverHandlers:function(){var a;f.forEach(this.layers,function(b){if(b.mouseMoveHandler)for(a in b.mouseMoveHandler)l.disconnect(b.mouseMoveHandler[a]);if(b.mouseOutHandler)for(a in b.mouseOutHandler)l.disconnect(b.mouseOutHandler[a])})},_createDynamicLayers:function(a){var b=[],c;f.forEach(a.dynamicLayerInfos||a.layerInfos,function(d){c={id:d.id};c.source=d.source&&d.source.toJson();
var e;a.layerDefinitions&&a.layerDefinitions[d.id]&&(e=a.layerDefinitions[d.id]);e&&(c.definitionExpression=e);var f;a.layerDrawingOptions&&a.layerDrawingOptions[d.id]&&(f=a.layerDrawingOptions[d.id]);f&&(c.drawingInfo=f.toJson());c.minScale=d.minScale||0;c.maxScale=d.maxScale||0;b.push(c)});return b},_getTemplateFromTypes:function(a,b){var c;for(c=0;c<a.length;c++)if(a[c].id==b&&a[c].templates&&0<a[c].templates.length)return a[c].templates[0];return null},_findParentGroup:function(a,b,c){var d,e=
b.dynamicLayerInfos||b.layerInfos;for(d=0;d<e.length;d++)if(c==e[d].id){-1<e[d].parentLayerId&&(w.set(v.byId(this.id+"_"+a+"_"+e[d].parentLayerId+"_group"),"display","block"),this._findParentGroup(a,b,e[d].parentLayerId));break}},_addSubLayersToHide:function(a){function b(c,d){var e=a.layer.dynamicLayerInfos||a.layer.layerInfos,g,h;for(g=0;g<e.length;g++)if(e[g].id===c&&e[g].subLayerIds)for(h=0;h<e[g].subLayerIds.length;h++){var k=e[g].subLayerIds[h];-1===f.indexOf(d,k)&&(d.push(k),b(k,d))}}a.layer.layerInfos&&
f.forEach(this.hideLayersInLegend[a.layer.id],function(c){b(c,this.hideLayersInLegend[a.layer.id])},this)},_isLayerInScale:function(a,b,c){var d,e=!0;if(a.legendResponse&&a.legendResponse.layers)for(d=0;d<a.legendResponse.layers.length;d++){var f=a.legendResponse.layers[d];if(b.id==f.layerId){var h,k;!a.minScale&&0!==a.minScale||!a.maxScale&&0!==a.maxScale?(0==f.minScale&&a.tileInfo&&(h=a.tileInfo.lods[0].scale),0==f.maxScale&&a.tileInfo&&(k=a.tileInfo.lods[a.tileInfo.lods.length-1].scale)):(h=Math.min(a.minScale,
f.minScale)||a.minScale||f.minScale,k=Math.max(a.maxScale,f.maxScale));if(0<h&&h<c||k>c)e=!1;break}}else if(a.minScale||a.maxScale)if(a.minScale&&a.minScale<c||a.maxScale&&a.maxScale>c)e=!1;return e},_getServiceTitle:function(a){var b=a._titleForLegend;b||(b=a.url,a.url?-1<a.url.indexOf("/MapServer")?(b=a.url.substring(0,a.url.indexOf("/MapServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/ImageServer")?(b=a.url.substring(0,a.url.indexOf("/ImageServer")),b=b.substring(b.lastIndexOf("/")+
1,b.length)):-1<a.url.indexOf("/FeatureServer")&&(b=a.url.substring(0,a.url.indexOf("/FeatureServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):b="",a.name&&(b=0<b.length?b+(" - "+a.name):a.name));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&a.vectorFieldPixelFilter&&(a=a.vectorFieldPixelFilter.outputUnit?this["NLS_"+a.vectorFieldPixelFilter.outputUnit]:this["NLS_"+a.vectorFieldPixelFilter.inputUnit],J.isDefined(a)&&(b+=" ("+a+")"));return x.encode(b)},_getEffectiveScale:function(a,
b){var c=b.minScale,d=b.maxScale;if(J.isDefined(b.parentLayerId)){var e=a.layerInfos,f=b.parentLayerId,h;for(h=e.length-1;0<=h;h--)if(e[h].id==f)if(0==c&&0<e[h].minScale?c=e[h].minScale:0<c&&0==e[h].minScale||0<c&&0<e[h].minScale&&(c=Math.min(c,e[h].minScale)),d=Math.max(d||0,e[h].maxScale||0),-1<e[h].parentLayerId)f=e[h].parentLayerId;else break}return{minScale:c,maxScale:d}},_isSupportedLayerType:function(a){return a&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===
a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass||"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass||"esri.layers.WFSLayer"===a.declaredClass||"esri.layers.CSVLayer"===a.declaredClass)?!0:!1},isHostedTileService:function(a){var b=
/(https?:)?\/\/services.*\.arcgis\.com/i;return"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass&&b.test(a.url)?!0:!1},getField:function(a,b,c){if(a.getField)return a.getField(b);if(c&&c.fields){var d;f.forEach(c.fields,function(a){a.name===b&&(d=a)});return d}return null}});k.mixin(H,{ALIGN_LEFT:0,ALIGN_RIGHT:1});h("extend-esri")&&k.setObject("dijit.Legend",H,T);return H});