// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.23/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/ReportContainerPagination.html":'\x3cdiv class\x3d"esriGEReportPlayer_reportContainerPagination"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"reportBackgroundDiv" class\x3d"reportContainerPagination_reportBackground"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"infographicPageDiv"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"pageNavigatorDiv" class\x3d"reportContainerPagination_pageNavigatorDiv"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"emptyPlaceholder" class\x3d"reportContainerPagination_emptyPlaceholder"\x3e${nls.infographicEmpty}\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/reportContainers/ReportContainerPagination","dojo/_base/declare dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/PageNavigator esri/dijit/geoenrichment/utils/DomUtil ../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ../themes/BackgroundThemeUtil ../themes/ReportThemes dojo/text!../templates/ReportContainerPagination.html dojo/i18n!../../../../../nls/jsapi".split(" "),
function(f,g,r,e,t,h,k,l,c,m,n,p,q,d){d=d.geoenrichment.dijit.ReportPlayer.ReportPlayer;return f([h,k],{templateString:q,nls:d,viewModel:null,themeContext:null,theme:null,parentWidget:null,maxBulletsLimit:10,documentOptions:null,infographicPage:null,pageNavigator:null,postCreate:function(){var a=this;this.inherited(arguments);this.infographicPage=this.viewModel.layoutBuilder.createElement("infographicPage",{viewModel:this.viewModel,themeContext:this.themeContext,theme:this.theme,parentWidget:this,
keepPagePosition:!1,onResized:function(b){a.onResized(b);a._renderBackgroundImage(a.infographicPage.getCurrentSectionBox())},onPageIndexChanged:function(b){a.pageNavigator.setCurrentPageIndex(b)}},this.infographicPageDiv);this.own(this.infographicPage);this.pageNavigator=(new l({showArrows:!1,getNumPages:function(){return a.infographicPage.getNumItems()},onPageChanged:function(b){a.showSlideAt(b)}})).placeAt(this.pageNavigatorDiv);this.own(this.pageNavigator);this._setEmptyState(!1)},_renderBackgroundImage:function(a){var b=
this.viewModel.getDocumentDefaultStyles(this.theme||this.themeContext);b&&(a&&(a={x:a.x-20,y:a.y+7}),e.set(this.reportBackgroundDiv,"backgroundColor",""),n.applyBackgroundImageFromSettings(this.reportBackgroundDiv,b.backgroundImage,{documentOptions:this.documentOptions,pos:a})||b.backgroundColor&&e.set(this.reportBackgroundDiv,"backgroundColor",b.backgroundColor))},resize:function(a,b){this.infographicPage.resize(a,b)},notifyShown:function(){this._pendingJson?(this.fromJson(this._pendingJson),!this._pendingJson&&
this.onPendingDataApplied()):this.infographicPage.notifyShown()},getCurrentSlideIndex:function(){return this.infographicPage.getCurrentPageIndex()},showSlideAt:function(a){this.infographicPage.setCurrentPageIndex(a)},showNextSlide:function(){this.infographicPage.showNextPage()},showPreviousSlide:function(){this.infographicPage.showPreviousPage()},_pendingJson:null,fromJson:function(a){this._renderBackgroundImage();if(this._canApplyJson()){this._pendingJson=null;this.documentOptions=a.documentOptions;
var b=a.theme&&a.theme.id!==p.GRAPHIC?a.theme:null;this.themeContext=this.infographicPage.themeContext=b&&b.id;this.theme=this.infographicPage.theme=b;a=m.collectSectionJsons(a,{backgroundForeground:!1});this._setEmptyState(!a.length);b=a.length>this.maxBulletsLimit;g[b?"add":"remove"](this.domNode,"hasCustomPaginationBullets");c[b?"show":"hide"](this.pageNavigatorDiv);return this.infographicPage.setItems(a).then(function(){this.pageNavigator.reset()}.bind(this))}this._pendingJson=a},_canApplyJson:function(){return c.isNodeInLayout(this.domNode)},
_setEmptyState:function(a){c.hide([this.infographicPageDiv,this.emptyPlaceholder,this.reportBackgroundDiv]);c.show(a?this.emptyPlaceholder:[this.infographicPageDiv,this.reportBackgroundDiv])},onResized:function(a){},onPendingDataApplied:function(){}})});