//>>built
define("dgrid1/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/dom-construct dojo/on dojo/when dojo/query ./util/misc".split(" "),function(G,H,I,J,m,K,L,N,w){function E(a){return a&&(0<=a.className.indexOf("dgrid-row")||0<=a.className.indexOf("dgrid-loading"))}function x(a){return a&&0<=a.className.indexOf("dgrid-preload")}var F=0;return I([G,H],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:0,pagingMethod:"debounce",
pagingDelay:w.defaultDelay,keepScrollPosition:!1,rowHeight:0,_deleteQueue:[],postCreate:function(){this.inherited(arguments);var a=this;K(this.bodyNode,"scroll",w[this.pagingMethod](function(b){a._processScroll(b)},null,this.pagingDelay))},renderQuery:function(a,b){var d=this,g=b&&b.container||this.contentNode,c,h,e,p,r=0,u=b&&b.start||0;"level"in a&&(r=p=a.level);c={query:a,count:0,level:r,top:!1};var n={node:m.create("div",{className:"dgrid-preload",style:{height:"0"}},g),count:0,query:a,next:c,
level:r,top:!0};h=n.node;h.rowIndex=0;c.previous=n;e=c.node=m.create("div",{className:"dgrid-preload",style:{height:"0"}},g);n.id=F++;h.setAttribute("data-preloadid",n.id);c.id=F++;e.setAttribute("data-preloadid",c.id);e.rowIndex=this.minRowsPerPage;d._insertPreload(n);var v=m.create("div",{className:"dgrid-loading"},e,"before");m.create("div",{className:"dgrid-below"},v).innerHTML=this.loadingMessage;b=J.mixin({start:0,count:this.minRowsPerPage},b);null!=p&&(b.queryLevel=p);return this._trackError(function(){var g=
a(b);return d.renderQueryResults(g,e,b).then(function(a){return g.totalLength.then(function(g){var f=a.length,k=e.parentNode;!d._rows||"queryLevel"in b||(d._rows.min=0,d._rows.max=f===g?Infinity:f-1);m.destroy(v);"queryLevel"in b||(d._total=g);0===g&&k&&(d.noDataNode&&m.destroy(d.noDataNode),d._insertNoDataNode(k));n.count=u;c.count=g-f-u;e.rowIndex=u+f;g?d._updatePreloadRowHeights(n):(e.style.display="none",h.style.display="none");d._previousScrollPosition&&k.offsetHeight&&(d.scrollTo(d._previousScrollPosition),
delete d._previousScrollPosition);return L(d._processScroll()).then(function(){return a})})}).otherwise(function(a){m.destroy(v);throw a;})})},_insertPreload:function(a){var b=this.preload;if(b){for(;b.node.compareDocumentPosition(a.node)&Node.DOCUMENT_POSITION_PRECEDING;)if(b=b.previous,null==b)return;for(;b.node.compareDocumentPosition(a.node)&Node.DOCUMENT_POSITION_FOLLOWING&&b.next;)b=b.next;b.previous.next=a;a.previous=b.previous;a=a.next;a.next=b;b.previous=a}else this.preload=a},refresh:function(a){var b=
this,d=a&&a.keepScrollPosition;"undefined"===typeof d&&(d=this.keepScrollPosition);d&&(this._previousScrollPosition=this.getScrollPosition());this.inherited(arguments);if(this._renderedCollection)return this.renderQuery(function(a){return b._renderedCollection.fetchRange({start:a.start,end:a.start+a.count})}).then(function(){b._emitRefreshComplete()})},resize:function(){this.inherited(arguments);this._processScroll()},cleanup:function(){this.inherited(arguments);this.preload=null},renderQueryResults:function(a){var b=
this.inherited(arguments),d=this._getRenderedCollection(this.preload);d&&d.releaseRange&&b.then(function(b){b[0]&&!b[0].parentNode.tagName&&a.totalLength.then(function(){d.releaseRange(b[0].rowIndex,b[b.length-1].rowIndex+1)})});return b},_getFirstRowSibling:function(a){return a.lastChild},_calcRowHeight:function(a){var b=a.nextSibling;return b&&!/\bdgrid-preload\b/.test(b.className)?b.offsetTop-a.offsetTop:a.offsetHeight},_calcAverageRowHeight:function(a){for(var b=a.length,d=0,g=0;g<b;g++)d+=this._calcRowHeight(a[g]);
return b&&d?d/b:0},_updatePreloadRowHeights:function(){var a=this.preload;if(a){for(;a.previous;)a=a.previous;for(;a;)a.rowHeight||(a.rowHeight=this.rowHeight||this._calcAverageRowHeight(a.node.parentNode.querySelectorAll(".dgrid-row")),this._adjustPreloadHeight(a)),a=a.next}},lastScrollTop:0,_processScroll:function(a){function b(a,b){for(var c=b?"next":"previous",d;d=a[c];)a=d;return a}function d(a,c){function d(){var b;a:{b=!c;for(var d=a;d=d[c?"previous":"next"];)if(b===d.top){b=d;break a}b=void 0}if(b&&
h!==b&&!x(b.top?b.node.nextSibling:b.node.previousSibling))return f(),a=b,m=a.node,k=c?a.node.offsetTop-u:r-(a.node.offsetTop+a.node.offsetHeight),p=(b=g(m))&&b.rowIndex,z=void 0,b}function g(a){var b=x(a);(a=a[M])&&!E(a)&&(a=b&&x(a)?null:(b=d())?b:g(a));return a}function f(){a.count+=n;c&&(m.rowIndex-=n);e._adjustPreloadHeight(a);n=0;e._releaseRange(a,c,p,z)}var h=a;a=b(a,c);var k=c?a.node.offsetTop-u:r-(a.node.offsetTop+a.node.offsetHeight),l=e.farOffRemoval,m=a.node,M=c?"previousSibling":"nextSibling",
n=0,q=0,p,z;if(k>2*l){var t;p=(t=g(m))&&t.rowIndex;for(z=void 0;t&&h!==a;){var v=e._calcRowHeight(t);q+v+l>k||!E(t)?t=d():(q+=v,n+=t.count||1,e._pruneRow(t,c),"rowIndex"in t&&(z=t.rowIndex),t=g(t))}f();e._deleteNodeQueue()}}function g(a,b){do a=b?a.next:a.previous;while(a&&!a.node.offsetWidth);return a}var c=this.preload,h;this._updatePreloadRowHeights();if(h=c&&c.rowHeight){var e=this,p=e.bodyNode,r=a&&a.scrollTop||this.getScrollPosition().y,u=p.offsetHeight+r,n;a=e.lastScrollTop;var p=e.bufferRows*
h,v=p-h,w,B=!0;for(e.lastScrollTop=r;c&&!c.node.offsetWidth;)c=c.previous;for(;c&&c!==n;){n=e.preload;e.preload=c;h=c.node;var f=h.offsetTop;if(u+1+v<f)c=g(c,B=!1);else if(r-1-v>f+h.offsetHeight)c=g(c,B=!0);else{var f=((h.top?r-p:u)-f)/c.rowHeight,l=(u-r+2*p)/c.rowHeight,l=l+Math.min(Math.abs(Math.max(Math.min((r-a)*c.rowHeight,e.maxRowsPerPage/2),e.maxRowsPerPage/-2)),10);h.top&&(f-=l);f=Math.max(f,0);10>f&&0<f&&l+f<e.maxRowsPerPage&&(l+=Math.max(0,f),f=0);l=Math.min(Math.max(l,e.minRowsPerPage),
e.maxRowsPerPage,c.count);if(0===l)c=g(c,B);else{var l=Math.ceil(l),f=Math.min(Math.floor(f),c.count-l),k={};c.count-=l;var q=h,A,y=e.queryRowsOverlap,C=!c.top&&c;C?(c.previous&&(d(c),0<f&&x(h.previousSibling)?(f=Math.min(c.count,f),c.previous.count+=f,e._adjustPreloadHeight(c.previous,!0),h.rowIndex+=f,y=0):l+=f,c.count-=f),k.start=h.rowIndex-y,k.count=Math.min(l+y,e.maxRowsPerPage),h.rowIndex=k.start+k.count):(c.next&&(q=h.nextSibling,d(c,!0),x(h.nextSibling)?(c.next.count+=c.count-f,c.next.node.rowIndex=
f+l,e._adjustPreloadHeight(c.next),c.count=f,y=0,q=c.next.node):A=!0),k.start=c.count,k.count=Math.min(l+y,e.maxRowsPerPage),k.scrollingUp=!0);A&&q&&q.offsetWidth&&(A=q.offsetTop);e._adjustPreloadHeight(c);"level"in c.query&&(k.queryLevel=c.query.level);if("queryLevel"in k||!(k.start>e._total||0>k.count)){var D=m.create("div",{className:"dgrid-loading",style:{height:l*c.rowHeight+"px"}},q,"before");m.create("div",{className:"dgrid-"+(C?"below":"above"),innerHTML:e.loadingMessage},D);D.count=l;e._trackError(function(){(function(a,
b,d){var g=c.query(k);w=e.renderQueryResults(g,a,k).then(function(c){var f=e._rows;!f||"queryLevel"in k||!c.length||(b?(f.max<=f.min&&(f.min=c[0].rowIndex),f.max=c[c.length-1].rowIndex):(f.max<=f.min&&(f.max=c[c.length-1].rowIndex),f.min=c[0].rowIndex));q=a.nextSibling;m.destroy(a);d&&q&&q.offsetWidth&&e.scrollTo({y:e.bodyNode.scrollTop+q.offsetTop-d});g.totalLength.then(function(a){"queryLevel"in k||(e._total=a,e._rows&&e._rows.max>=e._total-1&&(e._rows.max=Infinity));b&&(b.count=a-b.node.rowIndex,
e._adjustPreloadHeight(b))});e._processScroll();return c},function(b){m.destroy(a);throw b;})})(D,C,A)});c=c.previous}}}}return w}},_adjustPreloadHeight:function(a,b){a.node.style.height=this._calculatePreloadHeight(a,b)+"px"},_calculatePreloadHeight:function(a,b){return Math.min(a.count*a.rowHeight,b?Infinity:this.maxEmptySpace)},_pruneRow:function(a,b,d){this.removeRow(a,!0,d);this._queueNodeForDeletion(a)},_queueNodeForDeletion:function(a){this._deleteQueue.push(a)},_deleteNodeQueue:function(){for(var a=
document.createElement("div"),b=this._deleteQueue,d=b.length;d--;)a.appendChild(b[d]);this._deleteQueue=[];setTimeout(function(){m.destroy(a)},1)},_removePreloads:function(a){if(a&&a.length){var b=this,d=this._getHeadPreload();a.forEach(function(a){if(a=b._findPreload(a,d))a.previous&&(a.previous.next=a.next),a.next&&(a.next.previous=a.previous)})}},_getHeadPreload:function(){var a=this.preload;if(a)for(;a.previous;)a=a.previous;return a},_findPreload:function(a,b){b||(b=this._getHeadPreload());for(var d=
b;d;){if(d.node===a)return d;d=d.next}},_getRenderedCollection:function(){return this._renderedCollection},_releaseRange:function(a,b,d,g){if(a){var c=a.level;a=this._getRenderedCollection(a);null!=g&&a.releaseRange&&"number"===typeof d&&"number"===typeof g&&(b?a.releaseRange(g,d+1):a.releaseRange(d,g+1),this._rows&&!c&&(this._rows[b?"max":"min"]=g,this._rows.max>=this._total-1&&(this._rows.max=Infinity)))}}})});